stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: kirito:latest
  # Dummy kubeconfig file content as an environment variable
  # This should be stored securely in GitLab CI/CD variables
  KUBECONFIG_CONTENT: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: FAKE_CERTIFICATE_AUTHORITY_DATA
        server: FAKE_SERVER_ADDRESS
      name: fake-cluster
    contexts:
    - context:
        cluster: fake-cluster
        user: fake-user
      name: fake-context
    current-context: fake-context
    kind: Config
    preferences: {}
    users:
    - name: fake-user
      user:
        client-certificate-data: FAKE_CLIENT_CERTIFICATE_DATA
        client-key-data: FAKE_CLIENT_KEY_DATA

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - kind load docker-image $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - echo "$KUBECONFIG_CONTENT" > kubeconfig
    - export KUBECONFIG=$(pwd)/kubeconfig
    - kubectl apply -f kirito-deployment.yaml
  only:
    - main
  