apiVersion: apps/v1
kind: Deployment
metadata:
  name: kirito-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kirito
  template:
    metadata:
      labels:
        app: kirito
    spec:
      containers:
      - name: kirito
        image: kirito:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: kirito-service
spec:
  type: NodePort
  selector:
    app: kirito
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
